name: CI Test Gagal

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Ini Pasti Gagal
        run: exit 1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore packages
        run: nuget restore Uas.sln

      - name: Build
        run: msbuild Uas.sln /p:Configuration=Release
